name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: windows-2022

    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable


    - name: Build
      run: cargo build --release


    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: reacher-windows
        path: |
          target/release/*.exe